#  cloud:
#    config:
#      profile: ${config.profile.active}
spring:
  datasource:
    password: ims
    url: jdbc:h2:mem:imsdb
    username: ims
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  profiles:
#    active: dev
#    default: dev
    
COURSE-SERVICE:
  courseName: The Course Name Git Default 
  courseDescription: The Course Description Git Default
  
