eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
server:
  port: ${server.port}
spring:
  application:
    name: course-service
  config:
    import:
    - optional:configserver:http://localhost:8888  
  datasource:
    password: ims
    url: jdbc:h2:mem:imsdb
    username: ims
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
COURSE-SERVICE:
  courseName: The Course Name Git Default Profile
  courseDescription: The Course Description Git Default Profile
  
